apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: blog-web-services
  namespace: default # The namespace the app will use
  labels:
    app: blog-web-services
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dswoboda/blog-web-services:v0.1
            imagePullPolicy: IfNotPresent
          ports:
            - name: http
              port: 8080
          type: NodePort